# Generated by Django 3.0.7 on 2022-01-18 02:58

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import retina_grader.models
import uuid


class Migration(migrations.Migration):

    replaces = [('retina_grader', '0001_initial'), ('retina_grader', '0002_rectangle'), ('retina_grader', '0003_auto_20200618_0218'), ('retina_grader', '0004_auto_20200618_0224'), ('retina_grader', '0005_auto_20200626_0555'), ('retina_grader', '0006_auto_20200626_0556'), ('retina_grader', '0007_auto_20200708_0629'), ('retina_grader', '0008_document_name'), ('retina_grader', '0009_auto_20200710_0619'), ('retina_grader', '0010_auto_20200710_0628'), ('retina_grader', '0011_auto_20200710_0630'), ('retina_grader', '0012_auto_20200722_0509'), ('retina_grader', '0013_auto_20200722_0659'), ('retina_grader', '0014_auto_20200729_0626'), ('retina_grader', '0015_document_scale'), ('retina_grader', '0014_auto_20200729_2330'), ('retina_grader', '0016_merge_20200730_2256'), ('retina_grader', '0017_auto_20200803_0717'), ('retina_grader', '0018_auto_20201014_1305'), ('retina_grader', '0019_auto_20201020_0653')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.ImageField(blank=True, height_field='height', null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=retina_grader.models.get_file_location_path, width_field='width')),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('random_id', models.CharField(default='UNASSIGNED', max_length=20)),
                ('allocated_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(blank=True, choices=[('BITEWING', 'BITEWING'), ('PANAROMIC', 'PANAROMIC')], max_length=20, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('SCREENING', 'SCREENING'), ('GRADING', 'GRADING')], max_length=20, null=True)),
                ('scale', models.DecimalField(decimal_places=12, default=1.0, max_digits=16)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('accession_no', models.CharField(default='UNASSIGNED', max_length=100)),
                ('patient_id', models.CharField(default='UNASSIGNED', max_length=20)),
                ('view_position', models.CharField(default='UNASSIGNED', max_length=100)),
            ],
            options={
                'ordering': ['document'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GradingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('ui_control_type', models.CharField(choices=[('Label', 'Label'), ('Radio', 'Radio'), ('CheckBox', 'CheckBox'), ('Text', 'Text'), ('Select', 'Select'), ('Date', 'Date'), ('number', 'number'), ('TextArea', 'TextArea')], default='Text', max_length=20)),
                ('ui_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GradingField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='admin comment', max_length=100)),
                ('is_monitorred', models.BooleanField(default=False)),
                ('grading_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_grader.GradingType')),
                ('default_value', models.CharField(default='admin comment', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date of onset')),
                ('value', models.CharField(blank=True, default='Not Recorded', max_length=200, null=True, verbose_name='Observed values (if any)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_grader.Document')),
                ('grading_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_grader.GradingField')),
            ],
            options={
                'ordering': ['-grading_field__grading_type__ui_order'],
            },
        ),
        migrations.CreateModel(
            name='Rectangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.PositiveIntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_grader.Document')),
                ('depth', models.CharField(blank=True, default='Enamel up to DEJ', max_length=200, null=True, verbose_name='Depth of Caries')),
                ('site', models.CharField(blank=True, default='Occlusal', max_length=200, null=True, verbose_name='Site of Caries')),
                ('tooth', models.TextField(blank=True, default='unknown', null=True)),
                ('Supernumerary', models.CharField(blank=True, default='None', max_length=200, null=True, verbose_name='Supernumerary Tooth')),
                ('eruption', models.CharField(blank=True, default='Erupted', max_length=200, null=True, verbose_name='Eruption Status')),
                ('bone_number', models.CharField(blank=True, default='unknown', max_length=50, null=True)),
                ('fracture_on_current_view', models.CharField(blank=True, default='No', max_length=20, null=True)),
                ('fracture_on_other_view', models.CharField(blank=True, default='No', max_length=20, null=True)),
                ('view_type', models.CharField(blank=True, default='unknown', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradingValueSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Type I', 'Type I'), ('Type II', 'Type II'), ('Gestational', 'Gestational'), ('Other', 'Other'), ('Smoker', 'Smoker'), ('Ex Smoker', 'Ex Smoker'), ('Non Smoker', 'Non Smoker'), ('Diabetic Laser', 'Diabetic Laser'), ('Other Ocular Laser', 'Other Ocular Laser'), ('No Laser', 'No Laser'), ('6/60', '6/60'), ('6/36', '6/36'), ('6/24', '6/24'), ('6/18', '6/18'), ('6/9', '6/9'), ('6/6', '6/6'), ('6/5', '6/5'), ('CF', 'CF'), ('HM', 'HM'), ('LP', 'LP'), ('NLP', 'NLP'), ('Mild NPDR', 'Mild NPDR'), ('Moderate NPDR', 'Moderate NPDR'), ('Severe NPDR', 'Severe NPDR'), ('PDR', 'PDR'), ('No DR', 'No DR'), ('Unable to grade', 'Unable to grade'), ('Present', 'Present'), ('None', 'None'), ('Repeat photos in 24 months', 'Repeat photos in 2 years'), ('Repeat photos in 1 year', 'Repeat photos in 1 year'), ('Repeat photos in 6 months', 'Repeat photos in 6 months'), ('Review in clinic', 'Review in clinic'), ('Not Applicable', 'Not Applicable'), ('1 Week', '1 Week'), ('1 Month', '1 Month'), ('3 Months', '3 Months'), ('1 Year', '1 Year'), ('Not Recorded', 'Not Recorded'), ('Left', 'Left'), ('Right', 'Right'), ('Good', 'Good'), ('Poor', 'Poor'), ('Moderate', 'Moderate'), ('Correct', 'Correct'), ('Incorrect', 'Incorrect')], max_length=200)),
                ('grading_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_grader.GradingType')),
            ],
        ),
    ]
