# Generated by Django 3.0.7 on 2022-01-31 04:20

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import retina_grader.models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_grader', '0001_squashed_0019_auto_20201020_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rectangle',
            name='Supernumerary',
        ),
        migrations.RemoveField(
            model_name='rectangle',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='rectangle',
            name='eruption',
        ),
        migrations.RemoveField(
            model_name='rectangle',
            name='site',
        ),
        migrations.RemoveField(
            model_name='rectangle',
            name='tooth',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(blank=True, height_field='height', null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/war454/grader_images'), upload_to=retina_grader.models.get_file_location_path, width_field='width'),
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_grader.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('idx', models.IntegerField(blank=True, null=True)),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina_grader.Polygon')),
            ],
        ),
    ]
