# Generated by Django 3.1.7 on 2022-06-09 08:15

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import retina_grader.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retina_grader', '0003_auto_20220214_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(blank=True, height_field='height', null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/vig00a/code/local_media_root/sianno-xray-github/'), upload_to=retina_grader.models.get_file_location_path, width_field='width'),
        ),
        migrations.AlterField(
            model_name='document',
            name='purpose',
            field=models.CharField(blank=True, choices=[('SCREENING', 'SCREENING'), ('GRADING', 'GRADING'), ('ASSESSING', 'ASSESSING')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dental_ai_infer_module', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
