# Generated by Django 3.0.7 on 2022-10-18 05:22

import django.core.files.storage
from django.db import migrations, models
import retina_grader.models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_grader', '0003_auto_20220214_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectangle',
            name='annotation_type',
            field=models.CharField(blank=True, default='unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(blank=True, height_field='height', null=True, storage=django.core.files.storage.FileSystemStorage(location='./meh011/code_space/WRIST_XRAY/media_root/'), upload_to=retina_grader.models.get_file_location_path, width_field='width'),
        ),
    ]
