# Generated by Django 3.0.7 on 2022-11-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_grader', '0004_auto_20221018_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectangle',
            name='toe_number',
            field=models.CharField(blank=True, default='unknown', max_length=250, null=True),
        ),
    ]
