# Generated by Django 3.0.7 on 2022-11-23 03:39

import django.core.files.storage
from django.db import migrations, models
import retina_grader.models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_grader', '0005_rectangle_toe_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/vig00a/code/sianno-xray-github/media_root'), upload_to=retina_grader.models.get_file_location_path),
        ),
    ]
