# Generated by Django 3.0.7 on 2022-11-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_grader', '0006_auto_20221123_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='anatomy',
            field=models.CharField(default='Not Available', max_length=100),
        ),
    ]
