# Generated by Django 3.0.7 on 2023-06-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_grader', '0007_document_anatomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingvalueset',
            name='value',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Type I', 'Type I'), ('Type II', 'Type II'), ('Gestational', 'Gestational'), ('Other', 'Other'), ('Smoker', 'Smoker'), ('Ex Smoker', 'Ex Smoker'), ('Non Smoker', 'Non Smoker'), ('Diabetic Laser', 'Diabetic Laser'), ('Other Ocular Laser', 'Other Ocular Laser'), ('No Laser', 'No Laser'), ('6/60', '6/60'), ('6/36', '6/36'), ('6/24', '6/24'), ('6/18', '6/18'), ('6/9', '6/9'), ('6/6', '6/6'), ('6/5', '6/5'), ('CF', 'CF'), ('HM', 'HM'), ('LP', 'LP'), ('NLP', 'NLP'), ('Mild NPDR', 'Mild NPDR'), ('Moderate NPDR', 'Moderate NPDR'), ('Severe NPDR', 'Severe NPDR'), ('PDR', 'PDR'), ('No DR', 'No DR'), ('Unable to grade', 'Unable to grade'), ('Present', 'Present'), ('None', 'None'), ('Repeat photos in 24 months', 'Repeat photos in 2 years'), ('Repeat photos in 1 year', 'Repeat photos in 1 year'), ('Repeat photos in 6 months', 'Repeat photos in 6 months'), ('Review in clinic', 'Review in clinic'), ('Not Applicable', 'Not Applicable'), ('1 Week', '1 Week'), ('1 Month', '1 Month'), ('3 Months', '3 Months'), ('1 Year', '1 Year'), ('Not Recorded', 'Not Recorded'), ('Left', 'Left'), ('Right', 'Right'), ('Good', 'Good'), ('Poor', 'Poor'), ('Moderate', 'Moderate'), ('Correct', 'Correct'), ('Incorrect', 'Incorrect'), ('Ankle', 'Ankle'), ('Foot', 'Foot'), ('Forefoot', 'Forefoot'), ('Other', 'Other'), ('DP', 'DP'), ('Obl', 'Obl'), ('Lat', 'Lat')], max_length=200),
        ),
    ]
