# Generated by Django 3.0.7 on 2023-12-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_grader', '0008_auto_20230626_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectangle',
            name='osteomyelitis_present_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
