# Generated by Django 3.0.7 on 2024-02-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina_grader', '0009_rectangle_osteomyelitis_present_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rectangle',
            name='osteomyelitis_present_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
